baseURL = "https://toddheslin.com"
languageCode = "en-au"
title = "Todd Heslin - Full Stack Developer"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 8                                 # Set the number of posts to show before overflowing to the next page.
summaryLength = 20                           # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = ""

# Add your Disqus shortname here.
disqusShortname = ""

[taxonomies]
tag = "tags"

[author]
name = "Todd Heslin"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
unsafe = true

[params]
math = false
# Blog description at the top of the homepage. Supports markdown.
description = "I'm Todd, a full stack web developer living in Wellington, New Zealand. I build tools and apps for the web, mostly using Vue, Node, and Hasura. Check my setup [here](/uses) and follow me on Github [here](https://github.com/toddheslin)."
showReadMore = false

# Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
enableKofi = false
kofi = ""

# Add links to your accounts. Remove the ones you don't want to include.
# Main
# email = "#"
instagram = "https://www.instagram.com/beingremarkable/"
pinterest = "https://www.pinterest.nz/toddheslin/"
youtube = "https://www.youtube.com/c/ToddHeslin"

# Writing
# medium = "#"

# Programming
github = "https://github.com/toddheslin/"
# stackoverflow = "#"
# gitlab = "#"
# codepen = "#"

# Menu links along the sidebar navigation.
[[menu.main]]
identifier = "about"
name = "About me"
url = "/about/"
weight = 1           # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
identifier = "now"
name = "What am I working on?"
url = "/now/"
weight = 2

[[menu.main]]
identifier = "tunes"
name = "Tunes"
url = "/tunes/"
weight = 3

[[menu.main]]
identifier = "books"
name = "Books"
url = "/books/"
weight = 4

[[menu.main]]
identifier = "setup"
name = "Dev setup"
url = "/uses/"
weight = 5

[[menu.main]]
identifier = "contact"
name = "Get in touch"
url = "/contact/"
weight = 6

# [[menu.main]]
# 	identifier = "tags"
# 	name = "Tags"
# 	url = "/tags/"
# 	weight = 2

# [[menu.main]]
# 	name = "Archives"
# 	identifier = "archives"
# 	url = "/archives/"
# 	weight = 3

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
anonymizeIP = true
disable = true
respectDoNotTrack = true
useSessionStorage = false
[privacy.instagram]
disable = true
simple = false
[privacy.twitter]
disable = true
enableDNT = true
simple = false
[privacy.vimeo]
disable = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true
